# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-28 07:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteDemo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('age', models.CharField(max_length=5)),
                ('address', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=30)),
                ('weichat', models.CharField(max_length=30)),
                ('phone', models.CharField(max_length=30)),
            ],
        ),
    ]
