# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-02 09:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteDemo', '0002_lu'),
    ]

    operations = [
        migrations.CreateModel(
            name='rtable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sn', models.CharField(max_length=20)),
                ('product', models.CharField(max_length=30)),
                ('ip', models.CharField(max_length=30)),
                ('hostname', models.CharField(max_length=40)),
                ('machine', models.CharField(max_length=10)),
                ('os', models.CharField(max_length=30)),
                ('clone', models.CharField(max_length=30)),
                ('cpu_type', models.CharField(max_length=40)),
                ('cpu_phy', models.CharField(max_length=30)),
                ('cpu_cores', models.CharField(max_length=5)),
                ('mem', models.CharField(max_length=15)),
                ('disk', models.CharField(max_length=15)),
                ('status', models.CharField(max_length=5)),
            ],
        ),
    ]
