# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-06 02:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteDemo', '0003_rtable'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ecs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sn', models.CharField(max_length=20)),
                ('ip', models.CharField(max_length=30)),
                ('mount', models.CharField(max_length=10)),
                ('partition', models.CharField(max_length=10)),
                ('memory', models.CharField(max_length=10)),
                ('clone', models.CharField(max_length=30)),
            ],
        ),
    ]
