# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-13 11:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteDemo', '0004_ecs'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dbinfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('HOST', models.CharField(max_length=30)),
                ('PROT', models.CharField(max_length=5)),
                ('USER', models.CharField(max_length=20)),
                ('PASSWD', models.CharField(max_length=30)),
            ],
        ),
    ]
