# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-17 09:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('siteDemo', '0005_dbinfo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dbinfo',
            old_name='PROT',
            new_name='PORT',
        ),
        migrations.RenameField(
            model_name='ecs',
            old_name='clone',
            new_name='hostname',
        ),
        migrations.RenameField(
            model_name='ecs',
            old_name='memory',
            new_name='nc_id',
        ),
        migrations.RenameField(
            model_name='ecs',
            old_name='mount',
            new_name='status',
        ),
        migrations.RemoveField(
            model_name='ecs',
            name='partition',
        ),
    ]
