- {id: 1001-1, ip: 21.136.1.1, nc_cpu: !!python/long '70', nc_memory: !!python/long '220000',
  used_cpu: !!python/long '57', used_memory: !!python/long '218112'}
- {id: 1001-2, ip: 21.136.1.2, nc_cpu: !!python/long '70', nc_memory: !!python/long '220000',
  used_cpu: !!python/long '58', used_memory: !!python/long '219136'}
- {id: 1001-3, ip: 21.136.1.3, nc_cpu: !!python/long '70', nc_memory: !!python/long '220000',
  used_cpu: !!python/long '47', used_memory: !!python/long '161792'}
- {id: 1001-4, ip: 21.136.1.4, nc_cpu: !!python/long '70', nc_memory: !!python/long '220000',
  used_cpu: !!python/long '65', used_memory: !!python/long '217088'}
- {id: 1001-5, ip: 21.136.1.5, nc_cpu: !!python/long '70', nc_memory: !!python/long '220000',
  used_cpu: !!python/long '59', used_memory: !!python/long '219136'}
- {id: 1001-6, ip: 21.136.1.6, nc_cpu: !!python/long '70', nc_memory: !!python/long '220000',
  used_cpu: !!python/long '63', used_memory: !!python/long '173056'}
- {id: 1002-1, ip: 21.136.1.84, nc_cpu: !!python/long '40', nc_memory: !!python/long '200000',
  used_cpu: !!python/long '36', used_memory: !!python/long '114688'}
- {id: 1002-10, ip: 21.136.1.70, nc_cpu: !!python/long '40', nc_memory: !!python/long '200000',
  used_cpu: !!python/long '38', used_memory: !!python/long '96256'}
- {id: 1002-11, ip: 21.136.1.71, nc_cpu: !!python/long '40', nc_memory: !!python/long '200000',
  used_cpu: !!python/long '26', used_memory: !!python/long '79872'}
- {id: 1002-12, ip: 21.136.1.72, nc_cpu: !!python/long '40', nc_memory: !!python/long '200000',
  used_cpu: !!python/long '24', used_memory: !!python/long '96256'}
- {id: 1002-13, ip: 21.136.1.73, nc_cpu: !!python/long '40', nc_memory: !!python/long '200000',
  used_cpu: !!python/long '33', used_memory: !!python/long '64512'}
- {id: 1002-14, ip: 21.136.1.78, nc_cpu: !!python/long '40', nc_memory: !!python/long '200000',
  used_cpu: !!python/long '35', used_memory: !!python/long '152576'}
- {id: 1002-15, ip: 21.136.1.79, nc_cpu: !!python/long '40', nc_memory: !!python/long '200000',
  used_cpu: !!python/long '32', used_memory: !!python/long '61440'}
- {id: 1002-16, ip: 21.136.1.81, nc_cpu: !!python/long '40', nc_memory: !!python/long '200000',
  used_cpu: !!python/long '6', used_memory: !!python/long '10240'}
- {id: 1002-17, ip: 21.136.1.80, nc_cpu: !!python/long '40', nc_memory: !!python/long '200000',
  used_cpu: !!python/long '10', used_memory: !!python/long '18432'}
- {id: 1002-18, ip: 21.136.1.83, nc_cpu: !!python/long '40', nc_memory: !!python/long '200000',
  used_cpu: !!python/long '11', used_memory: !!python/long '19456'}
- {id: 1002-5, ip: 21.136.1.82, nc_cpu: !!python/long '40', nc_memory: !!python/long '200000',
  used_cpu: !!python/long '32', used_memory: !!python/long '59392'}
- {id: 1002-6, ip: 21.136.1.74, nc_cpu: !!python/long '40', nc_memory: !!python/long '200000',
  used_cpu: !!python/long '25', used_memory: !!python/long '148480'}
- {id: 1002-7, ip: 21.136.1.75, nc_cpu: !!python/long '40', nc_memory: !!python/long '200000',
  used_cpu: !!python/long '29', used_memory: !!python/long '55296'}
- {id: 1002-8, ip: 21.136.1.76, nc_cpu: !!python/long '40', nc_memory: !!python/long '200000',
  used_cpu: !!python/long '22', used_memory: !!python/long '92160'}
- {id: 1002-9, ip: 21.136.1.77, nc_cpu: !!python/long '40', nc_memory: !!python/long '200000',
  used_cpu: !!python/long '20', used_memory: !!python/long '36864'}
