{!!python/unicode 'login': !!python/unicode 'admin', !!python/unicode 'pass': !!python/unicode 'pa55word',
  !!python/unicode 'product': !!python/unicode 'dbOther', !!python/unicode 'url': !!python/unicode 'tianmu.tbsite.net'}
